#!/bin/bash

source pkgs.sh

pr_info "Building YouCompleteMe"
# Build YouCompleteMe
if [[ -d "~/.vim/bundle/YouCompleteMe" ]]; then
    cd "~/.vim/bundle/YouCompleteMe"
    ./install.sh --clang-completer
    wait
fi

pr_info "Updating bundles..."
echo "y\ny\ny\n" | vim +'NeoBundleCheck<\CR>' +'q'
wait
