#!/bin/bash

source pkgs.sh

mkdir -p ~/.vim/bundle
if [[ ! -d  ~/.vim/bundle/neobundle.vim ]]; then
    pr_info "Installing neobundle."
    git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
fi

export THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -f ~/.vimrc ]]; then
    pr_info "Backuping up the existing ~/.vimrc"
    mv --backup=numbered ~/.vimrc ~/.vimrc.bak
    pr_info "~/.vimrc backups: \n$(ls ~/.vimrc.bak*)"
fi

pr_info "Creating the new ~/.vimrc"
export PKGS_VIM_DIR="$(dirname $THIS_DIR/)/vim"
echo "set runtimepath=$PKGS_VIM_DIR,\$VIMRUNTIME" > ~/.vimrc
echo "source $PKGS_VIM_DIR/.vimrc" >> ~/.vimrc

pr_info "Updating bundles..."
echo "y\ny\ny\n" | vim +'NeoBundleInstall!<\CR>' +'q'
wait

source buildycm

pr_pass "Install complete"
