#!/bin/bash

source pkgs.sh

# Make sure we have an undos directory
mkdir -p ~/.vim/undos

pr_info "Updating bundles..."
echo "y\ny\ny\n" | vim +'NeoBundleCheck<\CR>' +'q'
wait

source buildycm.sh

pr_info "Building vimproc .so..."

cd ~/.vim/bundle/vimproc
make
cd - 
