#!/bin/bash

source pkgs.sh

# Make sure we have an undos directory
mkdir -p ~/.vim/undos

# Link our UltiSnips up
ln -nsf ${THIS_DIR}/../vim/UltiSnips ~/.vim/

pr_info "Updating bundles..."
echo "y\ny\ny\n" | vim +'NeoBundleCheck<\CR>' +'q'
wait

source buildycm.sh

# pr_info "Building vimproc .so..."

# cd ~/.vim/bundle/vimproc.vim
# make
# cd - 
